### PR TITLE
87 add suport to readOnly toggle

### LINKED ISSUE #87: Undo tries to save when readOnly is toggled to true
### Description

When you initialize the editorjs instance with `readOnly: false` and then later toggle it to true using `editor.readOnly.toggle()` then this library still tries to call `editor.save()` causing an error.

This error does not happen when `editorjs-undo` is not installed.

image

### Environment

* Editor.js version: 2.23.2
* Plugins you use with their versions:
```
    "@editorjs/embed": "2.5.0",
    "@editorjs/header": "2.6.2",
    "@editorjs/image": "2.6.2",
    "@editorjs/list": "1.6.2",
    "@editorjs/paragraph": "2.8.0",
    "@editorjs/table": "2.0.1",
    "editorjs-undo": "1.0.1",
```
* Device, Browser, OS: 
Device: Macbook M1 Pro
Browser: Chrome Version 98.0.4758.102 (Official Build) (arm64)
OS: macOS Monterey version 12.1

### Current behavior

Reproduction steps:
1. Create EditorJS instance with readOnly: false
2. Inject instance into Undo
3. Toggle editor to readOnly mode using editor.readOnly.toggle()
4. Observe the error

### Expected behavior

The library should know how to handle readOnly mode and respond accordingly when readOnly mode is toggled between true/false

### PR DESCRIPTION
**Pull request by MarioRodriguezS**
## Description 
Fix #87

At this moment, the toggle in readOnly is not causing any error in editorjs-undo as expected.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -105,10 +105,20 @@ export default class Undo {
...
   }
 
+  /**
+   * returns true if readOnly was toggled to true
+   * @returns {Node} Indirectly shows if readOnly was set to true or false
+   */
+  setReadOnly() {
+    const toolbox = document.querySelector('.ce-toolbox');
+    this.readOnly = !toolbox;
+  }
```
Comment (juanhurtado10) [inline src/index.js:115]: @MarioRodriguezS does this change require some test scenarios?

**Review by juanhurtado10 — CHANGES_REQUESTED** [review]

File: src/index.js (hunk 1 above)
Comment (MarioRodriguezS) [reply src/index.js:115]: @juanhurtado10 At this moment, there is a test to the readOnly mode consistent with the new feature, however we could test specifically the new feature. Thanks for the comment!

**Review by juanhurtado10 — APPROVED** [review]
