### PR TITLE
49 - accept strings in the holder key in editorjs-undo

### LINKED ISSUE #49: editorjs-undo not working with default editorjs configuration since 0.1.7
Hi 👋 

I update this morning to 0.1.7 and editorjs-undo stopped working. This is because my editorjs was configured with the default value for the `holder` param, which is `'editorjs'` (https://editorjs.io/getting-started#configuration).  It results in the following errors when instantiating Undo

```
bundle.js:280 Uncaught (in promise) TypeError: e.addEventListener is not a function
    at t.value (bundle.js:280)
    at new t (bundle.js:160)
    at onReady (fs_builder_controller.js:116)
    at editor.js:13098
 bundle.js:205 Uncaught (in promise) TypeError: Cannot read property 'undefined' of undefined
    at t.value (bundle.js:205)
    at bundle.js:199
 ```
 
Changing the configuration value of `holder` to `document.querySelector('#editorjs')` fixes the issue. I think editorjs-undo should support both a String or a HTMLElement value for the `holder` param, as this is what is supported by editorjs (see https://github.com/codex-team/editor.js/blob/master/types/configs/editor-config.d.ts#L16).

Let me know what you think. If you agree with my suggestion, I can go ahead and write a PR for this.

Cheers!

### PR DESCRIPTION
**Pull request by MarioRodriguezS**
Main issue: 
If editor.js was instanced with the default configuration (the holder key as 'editorjs'), editorjs-undo did not work. 

Solution: 
In the code, there was an error when some eventListeners were assigned to the holder value, when the holder was a string, they were been assigned to a string. The solution was to use the holder as the corresponding HTML element to the eventListeners.

- fix #49

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ export default class Undo {
     );
     observer.setMutationObserver();
 
-    this.setEventListeners();
+    this.setEventListeners(observer.holder);
```
Comment (juanhurtado10) [inline src/index.js:38]: @MarioRodriguezS The Observer holder and the **editorjs** holder element are different things, you can't use it in this way :)

File: src/index.js [hunk 2]
```diff
@@ -189,8 +189,8 @@ export default class Undo {
   /**
    * Sets events listeners to allow keyboard actions support.
    */
-  setEventListeners() {
-    const { holder } = this.editor.configuration;
```
Comment (juanhurtado10) [inline src/index.js:193]: @MarioRodriguezS  As you need to accept both (strings and DOM elements) I think a good approach could be:

```javascript
const holderElem = typeof holder === 'string' ? document.getElementById(holder) : holder
```

What do you think?

**Review by juanhurtado10 — CHANGES_REQUESTED** [review]

File: src/index.js [hunk 3]
```diff
@@ -23,6 +23,7 @@ export default class Undo {
 
     const { configuration } = editor;
 
+    this.holder = typeof configuration.holder === 'string' ? document.getElementById(configuration.holder) : configuration.holder;
```
Comment (juanhurtado10) [inline src/index.js:26]: @MarioRodriguezS you can use object destructing here

```javascript
const { holder } = configuration;

this.holder = typeof holder === 'string' ? document.getElementById(holder) : holder;
```

Comment (MarioRodriguezS) [reply src/index.js]: Done!. Thanks

**Comment by MarioRodriguezS** [comment]
Added the tests to the new features.

**Comment by juanhurtado10** [comment]
@MarioRodriguezS Outstanding 👏
